### ISSUE TITLE
Package installable from TestPyPi

### ISSUE THREAD

**Issue by GregoryPetrochenkov-NOAA** [NOAA-OWP/gval#80]
In anticipation of a public release of the repository, get the packaging tested and ready for official realease to PyPi.

## Current behavior
No available to download from TestPyPi.

## Expected behavior
Pip install via TestPyPi

`python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple gval`

**Comment by fernando-aristizabal** [comment]
@GregoryPetrochenkov-NOAA is this complete as it already works with TestPyPi? Can we close this issue and open up a new one to publish a versioned build to PyPi for the CIROH milestone?
